### PR TITLE
Update v3.28.0

### PR DESCRIPTION
**Pull request by LeandroStanger**
Overview of changes in 3.28.0
==============================

Changes since 3.26.1 stable version

* Meson port (IÃ±igo MartÃ­nez)
* Gettext port (IÃ±igo MartÃ­nez)
* Add shortcuts window (Jonathan Kang)
* Remember last application view style (Jonathan Kang)
* Add flatpak support (Mohammed Sadiq)
* Fix back button in trash view (Mohammed Sadiq)
* Fix crash when running X11 instead of Wayland (Mohammed Sadiq)
* Improve window geometry state (Mohammed Sadiq)
* Improve notes import on startup (Mohammed Sadiq)
* Improve import dialog (Mohammed Sadiq)
* Set default application icon (Mohammed Sadiq)
* Use g_auto* (Mohammed Sadiq)
* Widgets migration to GtkBuilder (Mohammed Sadiq)
* Code clean up (Mohammed Sadiq)
* Disable Zeitgeist support by default
* Adopt #pragma once
* Add support for Tracker2
* Fix owncloud saving issue
* Improve list view

Translations
* ca (Jordi Mas)
* cs (Marek ÄŒernockÃ½)
* da (Alan Mortensen / Ask Hjorth Larsen)
* de (Mario BlÃ¤ttermann / Tim Sabsch)
* el (Efstathios Iosifidis)
* es (Daniel Mustieles)
* fi (Jiri GrÃ¶nroos)
* fur (Fabio Tomat)
* gl (Fran Dieguez)
* hu (BalÃ¡zs Ãšr)
* id (Kukuh Syafaat / Andika Triwidada)
* it (Gianvito Cavasoli)
* kk (Baurzhan Muftakhidinov)
* ko (Changwoo Ryu / Hongmin Yang)
* lt (Aurimas ÄŒernius)
* lv (RÅ«dolfs Mazurs)
* nb (Kjartan Maraas)
* nl (Nathan Follens)
* pl (Piotr DrÄ…g)
* pt_BR (Rafael Fontenelle)
* sk (DuÅ¡an Kazik)
* sl (Matej UrbanÄiÄ)
* tr (Emin Tufan Ã‡etin)
* zh_TW (Cheng-Chia Tseng)

### CODE REVIEW

**Comment by igaldino** [comment]
test build bot

**Comment by TingPing** [comment]
bot, build

https://flathub.org/builds/#/builders/2/builds/179

**Comment by nedrichards** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
```
stat: cannot stat ‘builddir/*/share/app-info/xmls/org.gnome.bijiben.xml.gz’: No such file or directory
```

Shouldn't this be generated by appstream-compose?

**Pull request merged**
