### PR TITLE
use meson buildsystem

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Test build is here: https://flathub.org/builds/#/builders/2/builds/4162

**Comment by nedrichards** [comment]
Cool! Assume you'll be coming back to update to the new runtime and the other dependencies when they're released as well - but thanks for being quick off the mark!

**Comment by igaldino** [comment]
Yeah, I'll do that at once, after Wednesday ;)

**Pull request merged**
